import asyncio
import uuid
import re
from pathlib import Path
from datetime import datetime

import typer
from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel

import config
from context_engineering import memory
from context_engineering import memory


app = typer.Typer()
console = Console(width=100)  # Set consistent width for better formatting

# HELPER FUNCTIONS

def _normalize_content(content):
    """
    Normalize content to clean string, handling various formats from LLM responses.
    
    Handles:
    - List of parts (Gemini's format)
    - Dict with 'text' key
    - Plain strings
    - Objects with __str__ method
    """
    if content is None:
        return "No content available"
    
    # Handle list of parts (common in Gemini responses)
    if isinstance(content, list):
        parts = []
        for part in content:
            if isinstance(part, dict):
                # Extract text from dict
                if "text" in part:
                    parts.append(str(part["text"]))
                elif "content" in part:
                    parts.append(str(part["content"]))
                else:
                    # Fallback: convert entire dict to string
                    parts.append(str(part))
            elif isinstance(part, str):
                parts.append(part)
            else:
                parts.append(str(part))
        
        text = "\n\n".join(parts)
    elif isinstance(content, dict):
        # Handle dict with text/content key
        if "text" in content:
            text = str(content["text"])
        elif "content" in content:
            text = str(content["content"])
        else:
            text = str(content)
    else:
        # Handle string or other types
        text = str(content)
    
    # Clean up the text
    text = _clean_text(text)
    
    return text


def _clean_text(text: str) -> str:
    """
    Clean and normalize text output.
    
    - Remove excessive whitespace
    - Fix line breaks
    - Remove control characters
    - Normalize unicode
    """
    # Remove control characters except newlines and tabs
    text = re.sub(r'[\x00-\x08\x0B-\x0C\x0E-\x1F\x7F]', '', text)
    
    # Normalize multiple newlines to max 2
    text = re.sub(r'\n{3,}', '\n\n', text)
    
    # Remove trailing whitespace from each line
    lines = [line.rstrip() for line in text.split('\n')]
    text = '\n'.join(lines)
    
    # Remove leading/trailing whitespace from entire text
    text = text.strip()
    
    return text


def _format_report(text: str, ticker: str) -> str:
    """Format the report with proper structure and headers."""
    # Add header if not present
    if not text.startswith('#') and ticker.upper() not in text[:100]:
        header = f"# {ticker} - Equity Analysis Report\n\n"
        text = header + text
    
    return text


def _save_report_to_file(text: str, ticker: str, session_id: str) -> Path:
    """Save report to a markdown file."""
    reports_dir = Path("reports")
    reports_dir.mkdir(exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{ticker}_{timestamp}.md"
    filepath = reports_dir / filename
    
    # Format the report with metadata
    formatted_text = f"""# {ticker} - Equity Analysis Report

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Session ID:** {session_id}

---

{text}

---

*Report generated by IntrepidQ Equity Analysis System*
"""
    
    filepath.write_text(formatted_text, encoding='utf-8')
    return filepath

# CLI COMMANDS


@app.command()
def analyze(
    ticker: str,
    user_id: str = None,
    save_file: bool = typer.Option(True, "--save-file/--no-save-file", help="Save report to markdown file"),
    stream: bool = typer.Option(True, "--stream/--no-stream", help="Stream agent events in real-time")
):
    """
    Run multi-agent equity analysis on a stock ticker.
    
    Pipeline:
    1. Data Collection Agent (Financials, News, Search)
    2. Validation Agent (Data Quality Check)
    3. Analysis Agent (Investment Thesis)
    4. Synthesis Agent (Final Report)
    """
    user_id = user_id or config.DEFAULT_USER_ID
    ticker = ticker.upper().strip()

    console.print(f"\n[bold blue]🚀 Multi-Agent System: Analyzing {ticker}...[/bold blue]\n")

    session_id = f"analysis_{ticker}_{uuid.uuid4().hex[:6]}"

    async def _run():
        try:
            from agents import (
                run_data_collection,
                run_validation,
                run_analysis,
                run_synthesis
            )
            
            # --- Step 1: Data Collection ---
            console.print(Panel("[bold cyan]1. Data Collection Agent[/bold cyan]\nGathering financials, news, and strategic signals...", border_style="cyan"))
            data_result = await run_data_collection(ticker)
            console.print("[green]✓ Data Collection Complete[/green]\n")
            
            # --- Step 2: Validation ---
            console.print(Panel("[bold yellow]2. Validation Agent[/bold yellow]\nChecking data completeness and quality...", border_style="yellow"))
            validation_result = await run_validation(ticker, data_result)
            
            score = validation_result.get("completeness_score", 0)
            confidence = validation_result.get("confidence_level", "Unknown")
            console.print(f"[dim]Completeness: {score}% | Confidence: {confidence}[/dim]")
            console.print("[green]✓ Validation Complete[/green]\n")
            
            # --- Step 3: Analysis ---
            console.print(Panel("[bold magenta]3. Analysis Agent[/bold magenta]\nGenerating investment thesis and insights...", border_style="magenta"))
            analysis_result = await run_analysis(ticker, data_result)
            console.print("[green]✓ Analysis Complete[/green]\n")
            
            # --- Step 4: Synthesis ---
            console.print(Panel("[bold green]4. Synthesis Agent[/bold green]\nCompiling final report...", border_style="green"))
            final_report = await run_synthesis(ticker, analysis_result, validation_result, data_result)
            console.print("[green]✓ Synthesis Complete[/green]\n")
            
            # Format the report
            final_text = _format_report(final_report, ticker)

            # Display the report with rich formatting
            console.print("\n")
            console.print(Panel(
                Markdown(final_text),
                title=f"[bold cyan]📊 {ticker} Analysis Report[/bold cyan]",
                border_style="cyan",
                padding=(1, 2)
            ))
            console.print("\n[bold green]✅ Multi-Agent Analysis Complete![/bold green]\n")

            # Save to database
            await memory.save_analysis_to_memory(
                session_id=session_id,
                user_id=user_id,
                ticker=ticker,
                report=final_text,
            )
            
            # Save to file if requested
            if save_file:
                filepath = _save_report_to_file(final_text, ticker, session_id)
                console.print(f"[dim]💾 Report saved to: {filepath}[/dim]\n")

        except Exception as e:
            console.print(f"\n[bold red]❌ ERROR:[/bold red] {e}\n")
            import traceback
            traceback.print_exc()

    asyncio.run(_run())


@app.command()
def chat():
    """
    Minimal interactive mode: type 'analyze TICKER' or 'exit'.
    """
    console.print(
        "[bold green]💬 Chat Mode. Type 'analyze TICKER' or 'exit' to quit.[/bold green]\n"
    )

    while True:
        user_input = typer.prompt("You").strip()
        if user_input.lower() in ("exit", "quit"):
            console.print("[bold yellow]Goodbye![/bold yellow]")
            break

        if user_input.lower().startswith("analyze "):
            _, t = user_input.split(maxsplit=1)
            analyze(t)
        else:
            console.print("[yellow]Use 'analyze TICKER' or 'exit'.[/yellow]\n")


if __name__ == "__main__":
    app()
